export const DEL_CONTACT = 'DEL_CONTACT';
export const ADD_CONTACT = 'ADD_CONTACT';
export const UPD_CONTACT_ATTRIBUTE = 'UPD_CONTACT_ATTRIBUTE';
export const FETCH_CONTACTS_PENDING='FETCH_CONTACTS_PENDING';
export const FETCH_CONTACTS_FULFILLED = 'FETCH_CONTACTS_FULFILLED';
export const FETCH_CONTACTS_REJECTED = 'FETCH_CONTACTS_REJECTED';





