export const EXPAND_LEFT_SIDEBAR = 'EXPAND_LEFT_SIDEBAR';
export const COLLAPSE_LEFT_SIDEBAR = 'COLLAPSE_LEFT_SIDEBAR';
export const CLOSE_NEW_MAIL_WINDOW='CLOSE_NEW_MESSAGE_WINDOW';
export const OPEN_NEW_MAIL_WINDOW='OPEN_NEW_MESSAGE_WINDOW';
