export const DEL_MAIL = 'DEL_MAIL';
export const SEND_MAIL = 'SEND_MAIL';
export const UPD_MAIL_ATTRIBUTE = 'UPD_MAIL_ATTRIBUTE';
export const TOGGLE_OPEN_MAIL = 'TOGGLE_OPEN_MAIL';
export const FETCH_MAILS_PENDING='FETCH_MAILS_PENDING';
export const FETCH_MAILS_FULFILLED = 'FETCH_MAILS_FULFILLED';
export const FETCH_MAILS_REJECTED = 'FETCH_MAILS_REJECTED';





